apiVersion: v1
kind: Service
metadata:
  name: admin-backend
  labels:
    app.kubernetes.io/name: admin-backend
    app.kubernetes.io/part-of: homeease
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
