apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dora-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dora-exporter
  endpoints:
  - port: metrics
    interval: 60s
