image:
  repository: acrhomeeasedev01.azurecr.io/homeease/notification-service
  tag: not-yet-promoted
hpa:
  minReplicas: 2
workloadIdentity:
  enabled: true
  clientId: "REPLACE_ME_prod_notification_client_id"
keyVault:
  name: kv-homeease-prod-hs01
  tenantId: "REPLACE_ME_tenant_id"
secretProviderClass:
  enabled: true
extraLabels:
  homeease.io/environment: prod
  homeease.io/cloud: azure
