image:
  repository: acrhomeeasedev01.azurecr.io/homeease/frontend
  tag: 743190bbf973
ingress:
  host: homeease-app.centralindia.cloudapp.azure.com
  sslRedirect: true
  extraHostlessRule: false
extraLabels:
  homeease.io/environment: dev
  homeease.io/cloud: azure
resources:
  requests:
    cpu: 25m
