image:
  repository: acrhomeeasedev01.azurecr.io/homeease/frontend
  tag: not-yet-promoted
ingress:
  host: REPLACE_ME_prod_frontend_host
hpa:
  minReplicas: 2
extraLabels:
  homeease.io/environment: prod
  homeease.io/cloud: azure
