image:
  repository: acrhomeeasedev01.azurecr.io/homeease/frontend
  tag: fce17432f203
ingress:
  host: home.20-207-75-39.nip.io
  sslRedirect: false
  extraHostlessRule: true
extraLabels:
  homeease.io/environment: dev
  homeease.io/cloud: azure
resources:
  requests:
    cpu: 25m
