image:
  repository: acrhomeeasedev01.azurecr.io/homeease/frontend
  tag: d72879629ea7

ingress:
  host: app-demo.20-207-75-39.nip.io
  sslRedirect: false
  extraHostlessRule: false

extraLabels:
  homeease.io/environment: demo
  homeease.io/cloud: azure
