apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admin-frontend.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.publicService.enabled }}LoadBalancer{{ else }}ClusterIP{{ end }}
  selector:
    {{- include "admin-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
      protocol: TCP
