deploymentMode: SingleBinary

loki:
  auth_enabled: false

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  commonConfig:
    replication_factor: 1

  limits_config:
    retention_period: 720h # 30 days
    reject_old_samples: true

  compactor:
    retention_enabled: true
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 10Gi

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

test:
  enabled: false
lokiCanary:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

chunksCache:
  enabled: false
resultsCache:
  enabled: false
