apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeease-dev

resources:
  - ../../../base

labels:
  - pairs:
      homeease.io/environment: dev
      homeease.io/cloud: azure
    includeSelectors: false

images:
  - name: homeease/admin-backend
    newName: acrhomeeasedev.azurecr.io/homeease/admin-backend
    newTag: REPLACE-WITH-GIT-SHA

patches:
  - target:
      kind: Ingress
      name: admin-backend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: admin.dev.azure.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: admin.dev.azure.example.com
