image:
  repository: acrhomeeasedev01.azurecr.io/homeease/admin-frontend
  tag: fce17432f203
ingress:
  host: admin-console.52-140-83-144.nip.io
  sslRedirect: false
  extraHostlessRule: false
extraLabels:
  homeease.io/environment: dev
  homeease.io/cloud: azure
resources:
  requests:
    cpu: 25m
