image:
  repository: acrhomeeasedev01.azurecr.io/homeease/admin-frontend
  tag: 93917ef237a9
ingress:
  host: admin-console-staging.52-140-83-144.nip.io
  sslRedirect: false
  extraHostlessRule: false
extraLabels:
  homeease.io/environment: staging
  homeease.io/cloud: azure
resources:
  requests:
    cpu: 25m
