apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admin-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "admin-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
