apiVersion: v1
kind: Service
metadata:
  name: admin-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admin-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "admin-backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPortName }}
      protocol: TCP
