apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admin-backend.labels" . | nindent 4 }}
    {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  {{- end }}
