apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
