{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  {{- with .Values.extraLabels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  provider: {{ .Values.secretProviderClass.provider | default "azure" }}
  parameters:
  {{- if eq (.Values.secretProviderClass.provider | default "azure") "aws" }}
    region: {{ .Values.secretProviderClass.region | quote }}
    objects: |
      {{- range .Values.secretProviderClass.objects }}
      - objectName: {{ .awsSecret | quote }}
        objectType: secretsmanager
        objectAlias: {{ .envKey }}
      {{- end }}
  {{- else }}
    clientID: {{ .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.objects }}
        - |
          objectName: {{ .keyVaultObject }}
          objectType: secret
        {{- end }}
  {{- end }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.secretName }}
      type: Opaque
      data:
        {{- range .Values.secretProviderClass.objects }}
        - objectName: {{ if .awsSecret }}{{ .envKey }}{{ else }}{{ .keyVaultObject }}{{ end }}
          key: {{ .envKey }}
        {{- end }}
{{- end }}
